version: '2'
services:
    herokudemo-app:
        image: herokudemo
        external_links:
            - herokudemo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/HerokuDemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    herokudemo-postgresql:
        extends:
            file: postgresql.yml
            service: herokudemo-postgresql
