version: '2'
services:
    herokudemo-postgresql:
        container_name: herokudemo-postgresql
        image: postgres:9.5.4
        # volumes:
        #     - ~/volumes/jhipster/HerokuDemo/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=HerokuDemo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
